# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\'\n\x11PlaceOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\":\n\x12UpdateOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\"5\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\norder_date\x18\x02 \x01(\t2t\n\x0cOrderService\x12\x30\n\nPlaceOrder\x12\x12.PlaceOrderRequest\x1a\x0e.OrderResponse\x12\x32\n\x0bUpdateOrder\x12\x13.UpdateOrderRequest\x1a\x0e.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLACEORDERREQUEST']._serialized_start=15
  _globals['_PLACEORDERREQUEST']._serialized_end=54
  _globals['_UPDATEORDERREQUEST']._serialized_start=56
  _globals['_UPDATEORDERREQUEST']._serialized_end=114
  _globals['_ORDERRESPONSE']._serialized_start=116
  _globals['_ORDERRESPONSE']._serialized_end=169
  _globals['_ORDERSERVICE']._serialized_start=171
  _globals['_ORDERSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
