# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"N\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\norder_date\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\"\'\n\x11PlaceOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\":\n\x12UpdateOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x32i\n\x11PlaceOrderService\x12(\n\nPlaceOrder\x12\x12.PlaceOrderRequest\x1a\x06.Order\x12*\n\x0bUpdateOrder\x12\x13.UpdateOrderRequest\x1a\x06.Orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=17
  _globals['_ORDER']._serialized_end=95
  _globals['_PLACEORDERREQUEST']._serialized_start=97
  _globals['_PLACEORDERREQUEST']._serialized_end=136
  _globals['_UPDATEORDERREQUEST']._serialized_start=138
  _globals['_UPDATEORDERREQUEST']._serialized_end=196
  _globals['_PLACEORDERSERVICE']._serialized_start=198
  _globals['_PLACEORDERSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
